import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/say-exim-port-hero.jpg";
import { adminSessionKey, initialSiteData, storageKey, type Product, type SiteData } from "@/lib/say-exim-data";

type Page = "home" | "about" | "products" | "services" | "contact" | "categories" | "gallery" | "faq" | "testimonials" | "global-trade" | "privacy" | "terms" | "admin-login" | "admin" | "product";
const routePaths: Record<string, string> = { Home: "/", "About Us": "/about", Products: "/products", Services: "/services", Categories: "/categories", "Global Trade": "/global-trade", Gallery: "/gallery", FAQ: "/faq", Contact: "/contact" };
const faqs = [
  ["What products do you import and export?", "The catalogue covers industrial supplies, agricultural products, consumer goods, packaging, chemicals, construction materials, electronics and general merchandise."],
  ["What is the minimum order quantity?", "Minimum quantities depend on the product. Share your requirement to discuss suitable volumes."],
  ["Which countries do you ship to?", "Share your destination and product details so the relevant trade and shipping requirements can be discussed."],
  ["What are your payment terms?", "Payment arrangements are discussed in relation to the product and order. Contact the team for details."],
  ["Can you source products not listed on the website?", "Send your specifications through the enquiry form to discuss sourcing options."],
  ["Do you provide samples before bulk orders?", "Sample availability depends on the product. Include your request in an enquiry."],
];
const steps = ["Requirement discussion", "Product sourcing", "Supplier coordination", "Specifications review", "Documentation planning", "Shipment coordination"];
const iconFallback = (event: React.SyntheticEvent<HTMLImageElement>) => { event.currentTarget.src = heroImage; };
const slugify = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

function Brand({ compact = false }: { compact?: boolean }) {
  return <Link to="/" className={`brand-lockup ${compact ? "brand-compact" : ""}`} aria-label="SAY EXIM TRADERS home"><span className="brand-mark">S</span><span className="brand-copy"><strong>SAY EXIM</strong><small>TRADERS · PUNE, INDIA</small></span></Link>;
}

function Header() {
  const [open, setOpen] = useState(false);
  return <><div className="top-strip"><div className="site-container top-strip-inner"><span>Pune, Maharashtra, India</span><span><a href="tel:+919876543210">+91 98765 43210</a><i /> <a href="mailto:info@sayeximtraders.com">info@sayeximtraders.com</a></span></div></div><header className="site-header"><div className="site-container nav-inner"><Brand /><button className="menu-toggle" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open} onClick={() => setOpen(!open)}><span /><span /></button><nav className={open ? "main-nav nav-open" : "main-nav"} aria-label="Main navigation">{Object.entries(routePaths).map(([label, to]) => <Link key={label} to={to as "/"} onClick={() => setOpen(false)} activeProps={{ className: "nav-link active" }} className="nav-link">{label}</Link>)}<Button asChild variant="gold" size="sm"><Link to="/contact" onClick={() => setOpen(false)}>Request a quote <span aria-hidden="true">↗</span></Link></Button></nav></div></header></>;
}

function Footer({ data }: { data: SiteData }) {
  return <footer className="site-footer"><div className="site-container footer-grid"><div className="footer-brand"><Brand /><p>{data.content.aboutDescription}</p></div><div><h3>Explore</h3><div className="footer-links">{Object.entries(routePaths).slice(0, 6).map(([label, to]) => <Link key={label} to={to as "/"}>{label}</Link>)}<Link to="/privacy">Privacy policy</Link><Link to="/terms">Terms of service</Link></div></div><div><h3>Product categories</h3><div className="footer-links">{data.categories.filter((item) => item.visible).slice(0, 6).map((item) => <Link key={item.id} to="/products">{item.name}</Link>)}</div></div><div><h3>Get in touch</h3><div className="footer-links"><a href={`tel:${data.contact.phone.replaceAll(" ", "")}`}>{data.contact.phone}</a><a href={`mailto:${data.contact.email}`}>{data.contact.email}</a><span>{data.contact.address}</span></div><Link className="admin-footer-link" to="/admin/login">Admin Login <span aria-hidden="true">↗</span></Link></div></div><div className="site-container footer-bottom"><span>© {new Date().getFullYear()} {data.content.businessName}. All rights reserved.</span><span>{data.content.footerCredit}</span></div></footer>;
}

function SectionHeading({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy?: string; action?: React.ReactNode }) {
  return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div>{action}</div>;
}

function ProductCard({ product, onQuote }: { product: Product; onQuote: (name: string) => void }) {
  const category = initialSiteData.categories.find((item) => item.id === product.category)?.name ?? product.category;
  return <article className="product-card"><Link className="product-photo" to="/products/$slug" params={{ slug: slugify(product.name) }} aria-label={`View ${product.name}`}><img src={product.image} alt={product.name} loading="lazy" width={1100} height={760} onError={iconFallback} /><span className="photo-arrow" aria-hidden="true">↗</span></Link><div className="product-info"><span className="product-category">{category}</span><Link to="/products/$slug" params={{ slug: slugify(product.name) }} className="product-name">{product.name}</Link><p>{product.description}</p><div className="product-actions"><Link to="/products/$slug" params={{ slug: slugify(product.name) }}>View details <span aria-hidden="true">→</span></Link><button onClick={() => onQuote(product.name)} aria-label={`Request a quote for ${product.name}`}>Request quote</button></div></div></article>;
}

function ContactForm({ data, onSubmit }: { data: SiteData; onSubmit: (entry: SiteData["enquiries"][number]) => void }) {
  const [feedback, setFeedback] = useState("");
  const [selectedProduct, setSelectedProduct] = useState("");
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    onSubmit({ id: `e${Date.now()}`, name: String(form.get("name")), company: String(form.get("company")), email: String(form.get("email")), phone: String(form.get("phone")), product: String(form.get("product")), message: String(form.get("message")), status: "New", date: new Date().toISOString() });
    event.currentTarget.reset();
    setFeedback("Thank you. This demo enquiry is saved in this browser only and has not been sent to the business.");
  };
  return <form className="contact-form" onSubmit={handleSubmit}><div className="form-fields"><label>Full name<input name="name" required autoComplete="name" placeholder="Your name" /></label><label>Company name<input name="company" autoComplete="organization" placeholder="Company (optional)" /></label><label>Business email<input type="email" name="email" required autoComplete="email" placeholder="you@company.com" /></label><label>Phone number<input name="phone" autoComplete="tel" placeholder="Country code + number" /></label><label>Country<input name="country" placeholder="Your country" /></label><label>Product or service<select name="product" value={selectedProduct} onChange={(event) => setSelectedProduct(event.target.value)}><option value="">Select a product or service</option>{data.categories.map((category) => <option key={category.id}>{category.name}</option>)}{data.services.map((service) => <option key={service.id}>{service.name}</option>)}</select></label><label className="field-wide">Estimated quantity<input name="quantity" placeholder="Approximate volume" /></label><label className="field-wide">Business requirement<textarea name="message" required rows={4} placeholder="Tell us what you are looking for" /></label></div><Button type="submit" variant="gold">Send enquiry <span aria-hidden="true">↗</span></Button>{feedback && <p className="form-feedback" role="status">{feedback}</p>}<p className="form-note">Demo form only · enquiries are saved in this browser and are not delivered.</p></form>;
}

function HomePage({ data, onQuote, onEnquiry }: { data: SiteData; onQuote: (name?: string) => void; onEnquiry: (entry: SiteData["enquiries"][number]) => void }) {
  const featured = data.products.filter((product) => product.visible && product.featured).slice(0, 4);
  return <><section className="hero"><img className="hero-image" src={heroImage} alt="Container vessel and port cranes at sunset" width={1792} height={1024} /><div className="hero-shade" /><div className="site-container hero-content"><p className="eyebrow eyebrow-light">SAY EXIM TRADERS · PUNE, INDIA</p><h1>{data.content.heroTitle}</h1><p className="hero-description">{data.content.heroDescription}</p><div className="hero-actions"><Button asChild variant="gold"><Link to="/products">Explore products <span aria-hidden="true">↗</span></Link></Button><Button asChild variant="hero-outline"><Link to="/contact">Request a quote</Link></Button></div><div className="hero-footnote"><span>WHOLESALE · SOURCING · TRADE COORDINATION</span><span>INDIA <b>—</b> GLOBAL MARKETS</span></div></div></section>
    <section className="intro-section section-space"><div className="site-container intro-grid"><div className="intro-image-wrap"><img src={data.gallery[0]?.image ?? heroImage} alt="Trade containers ready for shipment" width={1100} height={760} loading="lazy" onError={iconFallback} /><span className="image-caption">A thoughtful approach to every trade requirement</span></div><div className="intro-copy"><p className="eyebrow">INTRODUCING SAY EXIM</p><h2>{data.content.aboutTitle}</h2><p>{data.content.aboutDescription}</p><Link className="text-link" to="/about">Discover our approach <span aria-hidden="true">→</span></Link><div className="values-row"><span>Integrity</span><span>Transparency</span><span>Long-term partnerships</span></div></div></div></section>
    <section className="categories-section section-space"><div className="site-container"><SectionHeading eyebrow="WHAT WE TRADE" title="Product categories" copy="A broad wholesale catalogue for business sourcing requirements." action={<Link className="text-link heading-link" to="/categories">View all categories <span aria-hidden="true">→</span></Link>} /><div className="category-grid">{data.categories.filter((item) => item.visible).slice(0, 4).map((category, index) => <Link key={category.id} to="/products" className="category-tile"><img src={category.image} alt={category.name} loading="lazy" width={1100} height={760} onError={iconFallback} /><span className="tile-index">0{index + 1}</span><span className="category-text"><strong>{category.name}</strong><small>{category.description}</small></span><span className="photo-arrow" aria-hidden="true">↗</span></Link>)}</div></div></section>
    <section className="featured-section section-space"><div className="site-container"><SectionHeading eyebrow="SELECTED CATALOGUE" title="Featured products" copy="Product examples from our wholesale catalogue. Availability is confirmed through enquiry." action={<Link className="text-link heading-link" to="/products">Browse catalogue <span aria-hidden="true">→</span></Link>} /><div className="product-grid">{featured.map((product) => <ProductCard key={product.id} product={product} onQuote={onQuote} />)}</div></div></section>
    <section className="services-band section-space"><div className="site-container"><SectionHeading eyebrow="HOW WE CAN HELP" title="Trade coordination, clearly handled" copy="Discuss your sourcing and wholesale requirements with the SAY EXIM team." action={<Link className="text-link heading-link" to="/services">Explore services <span aria-hidden="true">→</span></Link>} /><div className="service-grid">{data.services.filter((service) => service.visible).map((service, i) => <article className="service-item" key={service.id}><span className="service-num">0{i + 1}</span><h3>{service.name}</h3><p>{service.description}</p><Link to="/contact" className="service-link">Discuss your requirement <span aria-hidden="true">→</span></Link></article>)}</div></div></section>
    <section className="process-section section-space"><div className="site-container"><SectionHeading eyebrow="A CLEAR PROCESS" title="From enquiry to shipment planning" copy="Each requirement begins with a conversation about your product and business needs." /><div className="process-grid">{steps.map((step, i) => <div className="process-step" key={step}><span>0{i + 1}</span><h3>{step}</h3><i /></div>)}</div></div></section>
    <section className="image-ribbon" aria-label="Trade and logistics gallery">{data.gallery.slice(1, 7).map((image) => <img key={image.id} src={image.image} alt={image.alt} loading="lazy" width={1100} height={760} onError={iconFallback} />)}</section>
    <section className="cta-section"><div className="site-container cta-inner"><div><p className="eyebrow eyebrow-light">START A CONVERSATION</p><h2>Let’s discuss your next sourcing requirement.</h2></div><Button asChild variant="gold"><Link to="/contact">Contact our team <span aria-hidden="true">↗</span></Link></Button></div></section>
    <section className="contact-preview section-space"><div className="site-container contact-preview-grid"><div><p className="eyebrow">CONTACT SAY EXIM TRADERS</p><h2>Tell us what your business needs.</h2><p className="section-copy">We welcome wholesale, sourcing and international trade enquiries.</p><div className="contact-details"><a href={`tel:${data.contact.phone.replaceAll(" ", "")}`}>{data.contact.phone}</a><a href={`mailto:${data.contact.email}`}>{data.contact.email}</a><span>{data.contact.address}</span></div></div><ContactForm data={data} onSubmit={onEnquiry} /></div></section></>;
}

function PageBanner({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <section className="page-banner"><div className="site-container"><p className="eyebrow eyebrow-light">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div></section>; }

function ProductListing({ data, onQuote }: { data: SiteData; onQuote: (name?: string) => void }) {
  const [filter, setFilter] = useState("All categories");
  const [search, setSearch] = useState("");
  const products = data.products.filter((product) => product.visible && (filter === "All categories" || product.category === filter) && `${product.name} ${product.description}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageBanner eyebrow="WHOLESALE CATALOGUE" title="Products" copy="Explore product categories and send a business enquiry about your requirements." /><section className="site-container section-space"><div className="catalog-tools"><label className="search-control"><span>Search products</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search catalogue" /></label><label className="select-control"><span>Category</span><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>All categories</option>{data.categories.filter((item) => item.visible).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><span className="result-count">{products.length} products</span></div>{products.length ? <div className="product-grid catalog-grid">{products.map((product) => <ProductCard key={product.id} product={product} onQuote={onQuote} />)}</div> : <div className="empty-state"><h2>No matching products</h2><p>Try another search or category.</p></div>}</section></>;
}

function PageContent({ page, data, onQuote, onEnquiry }: { page: Page; data: SiteData; onQuote: (name?: string) => void; onEnquiry: (entry: SiteData["enquiries"][number]) => void }) {
  if (page === "home") return <HomePage data={data} onQuote={onQuote} onEnquiry={onEnquiry} />;
  if (page === "products" || page === "categories") return <ProductListing data={data} onQuote={onQuote} />;
  if (page === "about") return <><PageBanner eyebrow="ABOUT SAY EXIM" title="A considered approach to global trade" copy="A Pune-based import-export and wholesale trading business focused on reliable sourcing and clear communication." /><section className="site-container section-space about-detail"><div className="about-photo"><img src={data.gallery[2]?.image ?? heroImage} alt="Cargo handling at a modern port" loading="lazy" width={1100} height={760} onError={iconFallback} /></div><div><p className="eyebrow">WHO WE ARE</p><h2>{data.content.aboutTitle}</h2><p>{data.content.aboutDescription}</p><p>We work to understand each enquiry, discuss product specifications and coordinate the steps needed to move a trade requirement forward.</p><div className="values-list"><p><b>01</b><span><strong>Integrity</strong>Clear and considered business communication.</span></p><p><b>02</b><span><strong>Transparency</strong>Practical discussions around specifications and requirements.</span></p><p><b>03</b><span><strong>Partnership</strong>A relationship-led approach to wholesale trade.</span></p></div><Button asChild variant="gold"><Link to="/contact">Talk to our team <span aria-hidden="true">↗</span></Link></Button></div></section></>;
  if (page === "services") return <><PageBanner eyebrow="TRADE SERVICES" title="Services" copy="Practical coordination for sourcing and wholesale trade enquiries." /><section className="site-container section-space"><div className="service-detail-grid">{data.services.filter((item) => item.visible).map((service, i) => <article className="service-detail" key={service.id}><div className="service-detail-photo"><img src={service.image} alt={service.name} loading="lazy" width={1100} height={760} onError={iconFallback} /><span>0{i + 1}</span></div><div><p className="eyebrow">SAY EXIM SERVICES</p><h2>{service.name}</h2><p>{service.description}</p><Link className="text-link" to="/contact">Enquire about this service <span aria-hidden="true">→</span></Link></div></article>)}</div></section></>;
  if (page === "global-trade") return <><PageBanner eyebrow="GLOBAL TRADE" title="Trade begins with understanding." copy="We welcome sourcing and wholesale enquiries from businesses exploring cross-border trade." /><section className="site-container section-space"><div className="trade-lead"><p className="eyebrow">A SHARED PROCESS</p><h2>Coordinating the details, one step at a time.</h2><p>Trade routes and product availability depend on each enquiry. We discuss requirements, supplier options and shipment considerations with you directly.</p><img src={data.gallery[3]?.image ?? heroImage} alt="Cargo vessel and international freight operations" loading="lazy" width={1100} height={760} onError={iconFallback} /></div><div className="process-grid trade-steps">{steps.map((step, i) => <div className="process-step" key={step}><span>0{i + 1}</span><h3>{step}</h3><i /></div>)}</div><p className="disclaimer">Illustrative process only. Trade availability, routes, documentation and timing are confirmed for each enquiry.</p></section></>;
  if (page === "gallery") return <><PageBanner eyebrow="TRADE IN PICTURES" title="Gallery" copy="A selection of imagery representing products, logistics and wholesale trade." /><section className="site-container section-space"><div className="gallery-grid">{data.gallery.map((image) => <figure key={image.id}><img src={image.image} alt={image.alt} loading="lazy" width={1100} height={760} onError={iconFallback} /><figcaption><span>{image.category}</span>{image.title}</figcaption></figure>)}</div></section></>;
  if (page === "faq") return <><PageBanner eyebrow="COMMON QUESTIONS" title="Frequently asked questions" copy="Initial guidance for product and trade enquiries. Details depend on your specific requirement." /><section className="site-container section-space faq-list">{faqs.map(([question, answer], i) => <details key={question}><summary><span>0{i + 1}</span>{question}<b aria-hidden="true">+</b></summary><p>{answer}</p></details>)}</section></>;
  if (page === "testimonials") return <><PageBanner eyebrow="OUR APPROACH" title="Built on clear communication" copy="We value considered discussions, transparency and long-term business relationships." /><section className="site-container section-space testimonial-note"><div className="quote-mark">“</div><h2>Every trade enquiry starts with listening.</h2><p>We focus on understanding product needs and communicating clearly throughout the discussion.</p><Button asChild variant="gold"><Link to="/contact">Start an enquiry <span aria-hidden="true">↗</span></Link></Button></section></>;
  if (page === "contact") return <><PageBanner eyebrow="GET IN TOUCH" title="Contact SAY EXIM TRADERS" copy="Tell us about a product, sourcing or wholesale requirement." /><section className="site-container section-space contact-page-grid"><div className="contact-side"><p className="eyebrow">BUSINESS ENQUIRIES</p><h2>Let’s start a conversation.</h2><p>Share your requirements and contact details. This website demo does not send form submissions to the business.</p><div className="contact-details"><a href={`tel:${data.contact.phone.replaceAll(" ", "")}`}><small>PHONE</small>{data.contact.phone}</a><a href={`mailto:${data.contact.email}`}><small>EMAIL</small>{data.contact.email}</a><span><small>ADDRESS</small>{data.contact.address}</span><a target="_blank" rel="noreferrer" href={`https://maps.google.com/?q=${encodeURIComponent(data.contact.address)}`}><small>MAP</small>Open address in Maps ↗</a></div></div><ContactForm data={data} onSubmit={onEnquiry} /></section></>;
  if (page === "privacy" || page === "terms") return <><PageBanner eyebrow="SAY EXIM TRADERS" title={page === "privacy" ? "Privacy Policy" : "Terms of Service"} copy="Demo website information." /><section className="site-container section-space legal-copy"><h2>{page === "privacy" ? "Demo enquiry information" : "Website use"}</h2><p>{page === "privacy" ? "The enquiry form on this demonstration website stores entered details in the current browser only. It does not transmit them to SAY EXIM TRADERS." : "Product, service and trade information on this demonstration website is illustrative. Specifications, pricing, availability and terms must be confirmed directly with the business."}</p></section></>;
  if (page === "product") {
    const slug = typeof window === "undefined" ? "" : window.location.pathname.split("/").pop();
    const product = data.products.find((item) => slugify(item.name) === slug && item.visible);
    if (!product) return <><PageBanner eyebrow="CATALOGUE" title="Product not found" copy="This item may no longer be listed." /><div className="site-container section-space"><Button asChild variant="gold"><Link to="/products">Back to products</Link></Button></div></>;
    return <><PageBanner eyebrow={initialSiteData.categories.find((item) => item.id === product.category)?.name ?? "PRODUCT"} title={product.name} copy={product.description} /><section className="site-container section-space product-detail"><img src={product.image} alt={product.name} width={1100} height={760} onError={iconFallback} /><div><p className="eyebrow">PRODUCT ENQUIRY</p><h2>Discuss your requirements</h2><p>Specifications, availability and order quantities can be discussed based on your business needs.</p><Button variant="gold" onClick={() => onQuote(product.name)}>Request a quote <span aria-hidden="true">↗</span></Button><p className="disclaimer">Product information is illustrative. Details are confirmed during enquiry.</p></div></section></>;
  }
  return null;
}

type EditableList = "products" | "categories" | "services" | "gallery";
function AdminPanel({ data, setData, onLogout }: { data: SiteData; setData: React.Dispatch<React.SetStateAction<SiteData>>; onLogout: () => void }) {
  const [section, setSection] = useState("Overview");
  const [query, setQuery] = useState("");
  const [form, setForm] = useState<Record<string, string> | null>(null);
  const sections = ["Overview", "Products", "Categories", "Services", "Homepage", "Gallery", "Contact", "Enquiries", "Settings"];
  const visibleCount = (key: EditableList) => data[key].length;
  const updateData = (key: keyof SiteData, field: string, value: string | boolean) => setData((current) => ({ ...current, [key]: { ...current[key] as object, [field]: value } }));
  const beginAdd = () => setForm(section === "Products" ? { name: "", category: data.categories[0]?.id ?? "", description: "", image: "", featured: "false", visible: "true" } : section === "Categories" ? { name: "", description: "", image: "", visible: "true" } : section === "Services" ? { name: "", description: "", image: "", visible: "true" } : { title: "", category: "Products", image: "", alt: "", id: "", });
  const saveForm = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!form) return;
    const key = section.toLowerCase() as EditableList;
    const id = form.id || `${key}-${Date.now()}`;
    const item = key === "products" ? { ...form, id, featured: form.featured === "true", visible: form.visible === "true" } : key === "gallery" ? { ...form, id, alt: form.alt || form.title, category: form.category || "Products" } : { ...form, id, visible: form.visible !== "false" };
    setData((current) => ({ ...current, [key]: form.id ? current[key].map((entry) => entry.id === form.id ? item as never : entry) : [...current[key], item as never] }));
    setForm(null);
  };
  const deleteItem = (key: EditableList, id: string) => { if (window.confirm("Delete this item? This cannot be undone.")) setData((current) => ({ ...current, [key]: current[key].filter((entry) => entry.id !== id) })); };
  const editItem = (key: EditableList, item: Record<string, unknown>) => { setSection(key[0].toUpperCase() + key.slice(1)); setForm(Object.fromEntries(Object.entries(item).map(([field, value]) => [field, String(value ?? "")]))); };
  const listKey = section.toLowerCase() as EditableList;
  const isList = ["products", "categories", "services", "gallery"].includes(listKey);
  const filtered = isList ? data[listKey].filter((item) => JSON.stringify(item).toLowerCase().includes(query.toLowerCase())) : [];
  const settingFields = section === "Homepage" ? [["Hero title", "heroTitle"], ["Hero description", "heroDescription"], ["About title", "aboutTitle"], ["About description", "aboutDescription"]] : [["Business name", "businessName"], ["Footer credit", "footerCredit"]];
  return <div className="admin-layout"><aside className="admin-sidebar"><div className="admin-brand"><Brand compact /><span>CONTENT MANAGEMENT</span></div><nav>{sections.map((item) => <button className={section === item ? "admin-nav active" : "admin-nav"} key={item} onClick={() => { setSection(item); setForm(null); setQuery(""); }}>{item}<span aria-hidden="true">›</span></button>)}</nav><button className="admin-logout" onClick={onLogout}>Log out <span aria-hidden="true">↗</span></button></aside><main className="admin-main"><div className="admin-topbar"><span>SAY EXIM TRADERS <b>/</b> {section}</span><Link to="/">View website ↗</Link></div><div className="admin-content"><div className="admin-title"><div><p className="eyebrow">CONTENT MANAGEMENT</p><h1>{section}</h1></div>{isList && <Button variant="gold" onClick={beginAdd}>Add {section.slice(0, -1).toLowerCase()} +</Button>}</div>
    {section === "Overview" && <><div className="admin-stats">{[["Products", visibleCount("products")], ["Categories", visibleCount("categories")], ["Services", visibleCount("services")], ["Gallery images", visibleCount("gallery")], ["Demo enquiries", data.enquiries.length]].map(([label, count]) => <article key={label}><span>{label}</span><strong>{count}</strong></article>)}</div><div className="admin-overview"><h2>Recent demo enquiries</h2>{data.enquiries.length ? data.enquiries.slice(-5).reverse().map((entry) => <div className="enquiry-row" key={entry.id}><span><strong>{entry.name}</strong><small>{entry.product || "General enquiry"}</small></span><span>{entry.status}</span></div>) : <p>No demo enquiries saved yet.</p>}</div></>}
    {isList && <><div className="admin-toolbar"><input placeholder={`Search ${section.toLowerCase()}`} value={query} onChange={(event) => setQuery(event.target.value)} />{form && <button onClick={() => setForm(null)}>Cancel</button>}</div>{form && <form className="admin-edit-form" onSubmit={saveForm}><h2>{form.id ? "Edit item" : `Add ${section.slice(0, -1).toLowerCase()}`}</h2>{Object.entries(form).filter(([key]) => key !== "id").map(([key, value]) => <label key={key}>{key === "visible" || key === "featured" ? <><input type="checkbox" checked={value === "true"} onChange={(event) => setForm({ ...form, [key]: String(event.target.checked) })} /> {key}</> : key === "description" || key === "alt" ? <>{key}<textarea rows={3} value={value} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></> : <>{key}<input required={key === "name" || key === "title"} value={value} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></>}</label>)}<Button variant="gold" type="submit">Save changes</Button></form>}<div className="admin-table">{filtered.map((item) => <article key={item.id}><img src={"image" in item ? item.image : ""} alt="" onError={iconFallback} /><div><strong>{"name" in item ? item.name : item.title}</strong><small>{"category" in item ? item.category : "Content item"}</small></div><span className="admin-status">{"visible" in item ? item.visible ? "Visible" : "Hidden" : "Gallery"}</span><button onClick={() => editItem(listKey, item as unknown as Record<string, unknown>)}>Edit</button><button className="delete-action" onClick={() => deleteItem(listKey, item.id)}>Delete</button></article>)}{!filtered.length && <p className="admin-empty">No items to show.</p>}</div></>}
    {(section === "Homepage" || section === "Settings") && <form className="admin-settings" onSubmit={(event) => { event.preventDefault(); window.alert("Changes saved in this browser."); }}><h2>{section === "Homepage" ? "Homepage content" : "Website identity"}</h2>{settingFields.map(([label, key]) => <label key={key}>{label}<textarea rows={key.includes("Description") ? 4 : 2} value={data.content[key as keyof SiteData["content"]]} onChange={(event) => updateData("content", key, event.target.value)} /></label>)}{section === "Homepage" && <label>Hero banner image URL<input value={heroImage} readOnly /><small>The featured banner is bundled with this website.</small></label>}<Button variant="gold" type="submit">Save changes</Button><button type="button" className="reset-button" onClick={() => { if (window.confirm("Reset all demo content and enquiries to the original sample data?")) setData(initialSiteData); }}>Reset demo data</button></form>}
    {section === "Contact" && <form className="admin-settings" onSubmit={(event) => { event.preventDefault(); window.alert("Contact details saved in this browser."); }}><h2>Business contact details</h2>{[["Phone", "phone"], ["Email", "email"], ["Address", "address"]].map(([label, key]) => <label key={key}>{label}<textarea rows={key === "address" ? 3 : 1} value={data.contact[key as keyof SiteData["contact"]]} onChange={(event) => updateData("contact", key, event.target.value)} /></label>)}<Button variant="gold" type="submit">Save contact details</Button></form>}
    {section === "Enquiries" && <><div className="admin-toolbar"><input placeholder="Search enquiries" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="admin-table enquiry-table">{data.enquiries.filter((entry) => JSON.stringify(entry).toLowerCase().includes(query.toLowerCase())).map((entry) => <article key={entry.id}><div><strong>{entry.name}</strong><small>{entry.company || "Company not provided"} · {entry.email}</small><small>{entry.phone} · {entry.product}</small><p>{entry.message}</p></div><select value={entry.status} onChange={(event) => setData((current) => ({ ...current, enquiries: current.enquiries.map((item) => item.id === entry.id ? { ...item, status: event.target.value } : item) }))}><option>New</option><option>In progress</option><option>Closed</option></select><button className="delete-action" onClick={() => deleteItem("gallery", entry.id) && setData((current) => ({ ...current, enquiries: current.enquiries.filter((item) => item.id !== entry.id) }))}>Delete</button></article>)}{!data.enquiries.length && <p className="admin-empty">No demo enquiries yet. Enquiry form submissions appear here.</p>}</div><p className="local-note">Demo enquiries are stored in this browser only. They are not delivered to the business or shared between devices.</p></>}
    </div></main></div>;
}

function AdminLogin({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); if (email.trim().toLowerCase() === "admin" && password === "admin123") { localStorage.setItem(adminSessionKey, "1"); onLogin(); } else setError("Those demo login details don’t match. Please try again."); };
  return <main className="login-page"><div className="login-image"><img src={heroImage} alt="Container ship at a trading port" width={1792} height={1024} /><Link to="/" className="login-brand"><Brand /></Link><p>SAY EXIM TRADERS<br /><span>Import · Export · Wholesale</span></p></div><div className="login-panel"><Link className="login-back" to="/">← Back to website</Link><div className="login-form-wrap"><p className="eyebrow">CONTENT MANAGEMENT</p><h1>Admin login</h1><p>Sign in to manage website demo content.</p><form onSubmit={submit}><label>Email<input type="text" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="username" placeholder="admin" /></label><label>Password<span className="password-field"><input type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} required autoComplete="current-password" placeholder="Enter password" /><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? "Hide" : "Show"}</button></span></label>{error && <p className="login-error" role="alert">{error}</p>}<Button type="submit" variant="gold">Sign in <span aria-hidden="true">↗</span></Button></form><div className="credentials-hint"><strong>Demo access</strong><span>Email: admin</span><span>Password: admin123</span></div><p className="local-note">Demo access only. This browser-based login is not secure production authentication.</p></div></div></main>;
}

export function SayEximPage({ page }: { page: Page }) {
  const navigate = useNavigate();
  const [data, setData] = useState<SiteData>(initialSiteData);
  const [hydrated, setHydrated] = useState(false);
  const [adminActive, setAdminActive] = useState(false);
  useEffect(() => {
    try { const saved = localStorage.getItem(storageKey); if (saved) setData({ ...initialSiteData, ...JSON.parse(saved) as Partial<SiteData> }); setAdminActive(localStorage.getItem(adminSessionKey) === "1"); }
    catch { setData(initialSiteData); }
    setHydrated(true);
  }, []);
  useEffect(() => { if (hydrated) localStorage.setItem(storageKey, JSON.stringify(data)); }, [data, hydrated]);
  const pageTitle = useMemo(() => page.replace("-", " "), [page]);
  const addEnquiry = (entry: SiteData["enquiries"][number]) => setData((current) => ({ ...current, enquiries: [...current.enquiries, entry] }));
  const requestQuote = (name?: string) => {
    if (name) { navigate({ to: "/contact" }); sessionStorage.setItem("say-exim-product-request", name); }
    else navigate({ to: "/contact" });
  };
  if (page === "admin-login") return adminActive ? <AdminPanel data={data} setData={setData} onLogout={() => { localStorage.removeItem(adminSessionKey); setAdminActive(false); navigate({ to: "/admin/login" }); }} /> : <AdminLogin onLogin={() => { setAdminActive(true); navigate({ to: "/admin/dashboard" }); }} />;
  if (page === "admin") return adminActive ? <AdminPanel data={data} setData={setData} onLogout={() => { localStorage.removeItem(adminSessionKey); setAdminActive(false); navigate({ to: "/admin/login" }); }} /> : <AdminLogin onLogin={() => { setAdminActive(true); navigate({ to: "/admin/dashboard" }); }} />;
  return <div className="public-site" data-page={pageTitle}><Header /><PageContent page={page} data={data} onQuote={requestQuote} onEnquiry={addEnquiry} /><Footer data={data} /></div>;
}